name: Deploy to accounts

on:
  push:
    branches:
      - main
jobs:
  EricDeployment:
    runs-on: ubuntu-20.04
    name: EricDeployment
    environment: deployment-eric
    env:
      VITE_BASE: ~${{ secrets.SSH_USERNAME }}/reittisuunnittelu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #
      #      - name: Setup Node
      #        uses: actions/setup-node@v2
      #        with:
      #          node-version: 'v14.18.1'
      #          cache: 'npm'
      #
      #      - name: InstallDependencies
      #        run: npm install
      #
      #      - name: Build Project
      #        run: npm run build

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@edunix.metropolia.fi "mkdir -p ~/public_html/reittisuunnittelu"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -e "ssh -o StrictHostKeyChecking=no" -a --progress --delete ./src/ ${{ secrets.SSH_USERNAME }}@edunix.metropolia.fi:~/public_html/reittisuunnittelu

  MatiasDeployment:
    runs-on: ubuntu-20.04
    name: MatiasDeployment
    environment: deployment-matias
    env:
      VITE_BASE: ~${{ secrets.SSH_USERNAME }}/reittisuunnittelu
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      #
      #      - name: Setup Node
      #        uses: actions/setup-node@v2
      #        with:
      #          node-version: 'v14.18.1'
      #          cache: 'npm'
      #
      #      - name: InstallDependencies
      #        run: npm install
      #
      #      - name: Build Project
      #        run: npm run build

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@edunix.metropolia.fi "mkdir -p ~/public_html/reittisuunnittelu"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -e "ssh -o StrictHostKeyChecking=no" -a --progress --delete ./src/ ${{ secrets.SSH_USERNAME }}@edunix.metropolia.fi:~/public_html/reittisuunnittelu

  MikaDeployment:
    runs-on: ubuntu-20.04
    name: MikaDeployment
    environment: deployment-mika
    env:
      VITE_BASE: ~${{ secrets.SSH_USERNAME }}/reittisuunnittelu
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #      - name: Setup Node
      #        uses: actions/setup-node@v2
      #        with:
      #          node-version: 'v14.18.1'
      #          cache: 'npm'
      #
      #      - name: InstallDependencies
      #        run: npm install
      #
      #      - name: Build Project
      #        run: npm run build

      - name: Deploy
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@edunix.metropolia.fi "mkdir -p ~/public_html/reittisuunnittelu"
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -e "ssh -o StrictHostKeyChecking=no" -a --progress --delete ./src/ ${{ secrets.SSH_USERNAME }}@edunix.metropolia.fi:~/public_html/reittisuunnittelu
